ner:
  tag2idx:
    'B-problem': 1
    'B-treatment': 2
    'B-test': 8
    'I-problem': 3
    'I-treatment': 7
    'I-test': 5
    'X': 6
    'O': 9
    '[SEP]': 0
    '[CLS]': 4

  max_len: 204

clinical_trials:
  labeled:
    ClinicalTrials.2021-04-27.pt1: ../clinical_trials/labeled/ClinicalTrials.2021-04-27.pt1.labeled.json
    ClinicalTrials.2021-04-27.pt2: ../clinical_trials/labeled/ClinicalTrials.2021-04-27.pt2.labeled.json
    ClinicalTrials.2021-04-27.pt3: ../clinical_trials/labeled/ClinicalTrials.2021-04-27.pt3.labeled.json
    ClinicalTrials.2021-04-27.pt4: ../clinical_trials/labeled/ClinicalTrials.2021-04-27.pt4.labeled.json
    ClinicalTrials.2021-04-27.pt5: ../clinical_trials/labeled/ClinicalTrials.2021-04-27.pt5.labeled.json

sentence_encoder:
  type: 'specter'
  model: sentence-transformers/allenai-specter
  tokenizer: sentence-transformers/allenai-specter

embeddings:
  output_path: ../models/sentence_embeddings/sentence_transformer/
  filename: clinical_documents_specter_64.npz

clustering: 
  embedding_paths:
    - ../models/sentence_embeddings/word2vec/ClinicalTrials.2021-04-27.pt1.w2v_200.npz
    - ../models/sentence_embeddings/word2vec/ClinicalTrials.2021-04-27.pt2.w2v_200.npz
  feature_type: word2vec
  output_path: ../data/clusters
  model_type: kmeans
  filename: clinical_trials_w2v_100_clusters_kmeans_7comp.csv
  kmeans:
    model_params:
      n_clusters: 7
      max_iter: 50
      random_state: 42
  gmm:
    model_params:
      n_components: 7
      max_iter: 10
      random_state: 42
      covariance_type: diag
