ner:
  tag2idx:
    'B-problem': 1
    'B-treatment': 2
    'B-test': 8
    'I-problem': 3
    'I-treatment': 7
    'I-test': 5
    'X': 6
    'O': 9
    '[SEP]': 0
    '[CLS]': 4

  max_len: 204

topics:
  labeled: topics2021_labeled.json

clinical_trials:
  labeled:
    #topics: ../data/parsed_topics/topics2021_labeled.json
    ClinicalTrials.2021-04-27.pt1: ../data/clinical_trials/labeled/ClinicalTrials.2021-04-27.pt1.labeled.json
    ClinicalTrials.2021-04-27.pt2: ../data/clinical_trials/labeled/ClinicalTrials.2021-04-27.pt2.labeled.json
    ClinicalTrials.2021-04-27.pt3: ../data/clinical_trials/labeled/ClinicalTrials.2021-04-27.pt3.labeled.json
    ClinicalTrials.2021-04-27.pt4: ../data/clinical_trials/labeled/ClinicalTrials.2021-04-27.pt4.labeled.json
    ClinicalTrials.2021-04-27.pt5: ../data/clinical_trials/labeled/ClinicalTrials.2021-04-27.pt5.labeled.json

sentence_encoder:
  type: 'paraphrase'
  model: sentence-transformers/paraphrase-mpnet-base-v2
  tokenizer: sentence-transformers/paraphrase-mpnet-base-v2

embeddings:
  output_path: ../models/sentence_embeddings/sentence_transformer/
  filename: topics_paraphrase-mpnet-base-v2_64.npz

clustering: 
  embedding_paths:
    - ../models/sentence_embeddings/word2vec/ClinicalTrials.2021-04-27.pt1.w2v_200.npz
    - ../models/sentence_embeddings/word2vec/ClinicalTrials.2021-04-27.pt2.w2v_200.npz
  feature_type: word2vec
  output_path: ../data/clusters
  model_type: kmeans
  filename: clinical_trials_w2v_100_clusters_kmeans_7comp.csv
  kmeans:
    model_params:
      n_clusters: 7
      max_iter: 50
      random_state: 42
  gmm:
    model_params:
      n_components: 7
      max_iter: 10
      random_state: 42
      covariance_type: diag

rank: 
  document_embeddings: ../models/sentence_embeddings/sentence_transformer/clinical_documents_LaBSE.npz 
  topic_embeddings: ../models/sentence_embeddings/sentence_transformer/topics_LaBSE_64.npz
  k: 1000
  output_path: ../data/results/results_LaBSE.txt
  run_name: LaBSE_embeddings